[project]
name = "gsd"
version = "0.1.0"
description = "WASM app to plot grain-size distribution data"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "marimo>=0.17.7",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
]

[tool.uv]
cache-dir=".uv-cache"
